INSULTS = {
    0: "Don't talk about yourself so much ... we'll do that when you leave",
    1: "I would insult you back but Mother Natures has already done such a fine job, I just couldn't compete.",
    2: "I'm a lot better than what you have to look at in the mirror every morning",
    3: "I thought I said goodbye to you this morning when I flushed the toilet",
    4: "Funny you should call me an ugly bitch, your daddy likes to call me princess and other beautiful names, while he is dry humping my leg",
    5: "I love it when you call me by your mom's name... Turns me on.",
    6: "I could eat a whole bowl of alphabet soup, shit it out, and have something better than u just said.",
    7: "Look who's talking about themselves again",
    8: "See ya and take care.. and by see ya I mean go fuck yourself and by take care I mean go fuck yourself.",
    9: "People say laughter is the best medicine. Your face must be curing the world.",
    10: "Sometimes the first step to forgiveness is understanding that the other person is a complete idiot.",
    11: "The fact that jellyfish survived for 650 million years with no brains is good news for stupid people like you",
    12: "Zombies are looking for brains. Don't worry. You're safe.",
    13: "Somewhere out there is a tree, tirelessly producing oxygen so you can breath. I think you own it an apology",
    14: "Well..fuck you very much",
    15: "If you spoke your mind, you would be speechless",
    16: "I would tell you to eat trash but that's cannibalism",
    17: "I can fix my ugliness with plastic surgery but you on the other hand will stay stupid forever",
    18: "Acting like a dick won't make yours any bigger",
    19: "If I wanted to hear from an asshole, I would have farted",
    20: "Roses are red. Violets are blue. God made us beautiful. What the fuck happened to you?",
    21: "You remind me of a penny, two faced and fucking worthless!",
    22: "You're living proof that abortion should be legal",
    23: "I was going to give you a nasty look but I see you already have one.",
    24: "I'd like to see things from your point of view but I can't seem to get my head that far up my ass.",
    25: "I'd agree with you, but then we'd both be wrong.",
    26: "You're just mad because Miley Cyrus has a longer Dick than you do",
    27: "I'm sorry what'd you say? I have an ear disease called I don't care.",
    28: "If the 'you are what you eat' saying is true, then you must be a dick.",
    29: "I'm sorry I didn't get that.. I don't speak idiot",
    30: "If you're going to be two faced, at least make on of them pretty",
    31: "I'd slap you, but that would be animal abuse",
    32: "Out of millions of sperm, you were the fastest?",
    33: "Hey, Rainman called. He wants his social skills back",
    34: "I like you, you remind me of how it feels after I drop a huge deuce in the toilet",
    35: "Someone got up on the wrong side of the cage this morning",
    36: "You should do some soul-searching. Maybe you'll find one.",
    37: "If I throw a stick, will you leave?",
    38: "I could say nice things about you, but I would rather tell the truth.",
    39: "I know I'm talking like an idiot. I have to, other wise you wouldn't understand me.",
    40: "I hope your day is as pleasant as you are.",
    41: "I've been called worse things by better people.",
    42: "I wish we could be better strangers.",
    43: "There are two kinds of people in this world; people who care what you think, and people like me.",
    44: "You're so dumb, your brain cell died of loneliness",
    45: "Shouldn't you be out on a ledge somewhere?",
    46: "You're not stupid, your just possessed by a retarded ghost",
    47: "You shouldn't let your mind wander..its way to small to be out on its own",
    48: "I don't know what makes you so dumb, but its working",
    49: "Next time you shave, try standing an inch or two closer to the blade",
    50: "Roses Are Red Violets Are Blue, I got 5 Fingers The Middle One Is For You",
    51: "You should put the diaper on your mouth, that's where the craps comin' out.",
    52: "Sometimes I wonder if your butt is jealous of all the crap that comes out of your mouth.",
    53: "If you're waiting for me to care, you better pack a lunch. It's gonna be a while",
    54: "You would be much more likable if it wasn't for that hole in your mouth that noise comes out of.",
    55: "I'm fat because every time I did your mom she gave me a cookie",
    56: "If you got a problem, take it up with my ass because that the only thing that give a crap",
    57: "You should wear a condom on your head because if you're going act like a dick, you might as well dress like one",
    58: "I'm sorry, talking with you sounds about as appealing as playing leapfrog with unicorns",
    59: "Why don't you go outside and play hide and go fuck yourself",
    60: "I can't seem to find my dick.. mind if I look you your mothers mouth",
    61: "I refuse to engage in a battle of wits as I will not take advantage of the handicapp",
    62: "If ignorance it bliss, you must be the happiest person on earth",
    63: "Some babies were dropped on their heads but clearly you were thrown at the wall",
    64: "Could you go away please, I'm allergic to fuckwads",
    65: "Life is like toilet paper, you're either on a role or your taking shit from some asshole",
    66: "There is a fine line between sarcasm or just being an asshole",
    67: "If I wanted to be a bitch, all I would need to do is act like you",
    68: "If you're going to act like a turd, go lie in the yard",
    69: "Why do you keep coming back to me? You're like herpes",
    70: "What died on your neck? Oh, it's your head",
    71: "Why don't you shut up and give that hole in your face a chance to heal",
    72: "If you had any intelligence to question I would have questioned it already.",
    73: "I wish I had a lower I.Q,  maybe then I could enjoy your company.",
    74: "My mother is more of a man then you..and she's a woman",
    75: "I''m sorry, were you talking to me? I can't hear you over the ugly of your face.",
    76: "I don't have the time or energy to sink to your level; you have a nice day though.",
    77: "I would answer you back but life is too short, just like your dick",
    78: "Mirrors don't lie. Lucky for you, they can't laugh either.",
    79: "We're you always this stupid or did you take lessons",
    80: "So are you an asshole by choice or were you born that way?"
}
